// Code generated by mockery v1.0.0. DO NOT EDIT.

// Regenerate this file using `make store-mocks`.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/mattermost/mattermost-server/model"
import store "github.com/mattermost/mattermost-server/store"

// PostUnreadStore is an autogenerated mock type for the PostUnreadStore type
type PostUnreadStore struct {
	mock.Mock
}

// GetUnreadsByUserAndRootId provides a mock function with given fields: unread
func (_m *PostUnreadStore) GetUnreadsByUserAndRootId(unread *model.PostUnread) store.StoreChannel {
	ret := _m.Called(unread)

	var r0 store.StoreChannel
	if rf, ok := ret.Get(0).(func(*model.PostUnread) store.StoreChannel); ok {
		r0 = rf(unread)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(store.StoreChannel)
		}
	}

	return r0
}

// View provides a mock function with given fields: unread
func (_m *PostUnreadStore) View(unread *model.PostUnread) store.StoreChannel {
	ret := _m.Called(unread)

	var r0 store.StoreChannel
	if rf, ok := ret.Get(0).(func(*model.PostUnread) store.StoreChannel); ok {
		r0 = rf(unread)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(store.StoreChannel)
		}
	}

	return r0
}
